######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 24 15:41:07 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += goodwidget.h mainwin.h
SOURCES += goodwidget.cpp main.cpp mainwin.cpp
