######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 25 11:17:41 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainWin.h
SOURCES += mainWin.cpp
